stages:
- test
- build
- deploy

test:
    stage: test
    script:
    - ./activator test

build:
    stage: build
    script:
    - ./activator dist
    - cp target/universal/it4all-0.9.0.zip /home/gitlab-runner/artifacts/

deploy_stage:
    stage: deploy
    dependencies:
    - build
    script:
    - unzip /home/gitlab-runner/artifacts/it4all-0.9.0.zip -d /home/bjorn/dist/
    - cd /home/bjorn/dist
    - docker-compose up -d
    environment:
        name: stage-ls6
        url: 132.187.15.170

deploy_prod:
    stage: deploy
    dependencies:
    - build
    script:
    - echo "TODO deployment prod"
    environment:
        name: prod-ls6
        url: 132.187.15.133 / www.it4all2.informatik.uni-wuerzburg.de
    when: manual
    only:
    - master