image: beyselein/it4all-play-dockerfile

stages:
  - build-client
  - test

build-client:
  stage: build-client
  script:
    - cd react-ui
    - npm install
    - npm run build

test:
  stage: test
  script:
    - echo $CHROME_BIN
    - ls -al
    - cd ..
    - sbt test
