image: beyselein/play-dockerfile

services:
- it4all

stages:
- test
- build
- deploy

test:
    stage: test
    script:
    - ./activator test

build:
    stage: build
    script:
    - ./activator dist
    - cp target/universal/it4all-0.9.0.zip ~/artifacts/
    - cp docker-compose-dist.yml ~/dist/docker-compose.yml
    - cp Dockerfile ~/dist/Dockerfile

deploy_stage:
    stage: deploy
    dependencies:
    - build
    script:
    - unzip -uo ~/artifacts/it4all-0.9.0.zip -d ~/dist/
    - cd ~/dist
    - docker build -t play --build-arg USERNAME=$(whoami) .
    - docker-compose up -d
    environment:
        name: stage-ls6
        url: 132.187.15.170

deploy_prod:
    stage: deploy
    dependencies:
    - build
    script:
    - echo "TODO deployment prod"
    environment:
        name: prod-ls6
        url: 132.187.15.133 / www.it4all2.informatik.uni-wuerzburg.de
    when: manual
    only:
    - master