image: beyselein/play-dockerfile

stages:
- test
- build

test:
    stage: test
    script:
    - sbt test

build:
    stage: build
    script:
    - sbt dist

cache:
    paths:
    - ~/.ivy2
    - ~/.sbt