image: docker pull gafiatulin/alpine-sbt

stages:
- test
- build

test:
    stage: test
    script:
    - sbt test

build:
    stage: build
    script:
    - sbt dist

cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
    - ~/.ivy2/*
    - ~/.sbt/*