stages:
- test
- build
- deploy

test:
    stage: test
    script:
    - ./activator test

build:
    stage: build
    script:
    - ./activator dist

deploy_stage:
    stage: deploy
    script:
    - echo "TODO deployment stage"
    environment:
        name: stage-ls6
        url: 132.187.15.170

deploy_prod:
    stage: deploy
    script:
    - echo "TODO deployment prod"
    environment:
        name: prod-ls6
        url: 132.187.15.133 / www.it4all2.informatik.uni-wuerzburg.de
    when: manual
    only:
    - master