image: beyselein/play-dockerfile

stages:
- test
- build

test:
    stage: test
    script:
    - sbt test

build:
    stage: build
    script:
    - sbt dist

cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
    - "sbt-cache/.ivy.cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"
    - ~/.ivy2/
    - ~/.sbt/