image: beyselein/it4all-play-dockerfile

stages:
  - build-client
  - test

build-client:
  stage: build-client
  script:
    - cd client
    - npm install
    - npm run build:prod

test:
  stage: test
  script:
    - cd server
    - sbt test
