version: "3.3"

volumes:
  sql_main_volume: {}
  select_db_volume: {}
  update_db_volume: {}
  create_db_volume: {}

services:
  resources:
    image:        ls6uniwue/it4all-resources:0.4.9
    restart:      always
    ports:
      - 5050:5000

  webtester:
    image:        httpd:alpine
    restart:      always
    ports:
      - 9080:80
    volumes:
      - type:     bind
        source:   ./data/web/solutions/
        target:   /usr/local/apache2/htdocs/

  sqlmain:
    image:        mariadb
    restart:      always
    ports:
      - 3106:3306
    volumes:
      - type:     bind
        source:   ./conf/inits/db_main_init.sql
        target:   /docker-entrypoint-initdb.d/db_init_main.sql
      - type:     bind
        source:   sql_main_volume
        target:   /var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  sqlselect:
    image:        mariadb
    restart:      always
    ports:
      - 3107:3306
    volumes:
      - type:     bind
        source:   ./conf/inits/init_db_scripts/
        target:   /docker-entrypoint-initdb.d/
      - type:     volume
        source:   select_db_volume
        target:   /var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  sqlchange:
    image:        mariadb
    restart:      always
    ports:
      - 3108:3306
    volumes:
      - type:     bind
        source:   ./conf/inits/init_db_scripts/
        target:   /docker-entrypoint-initdb.d/
      - type:     volume
        source:   update_db_volume
        target:   /var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  sqlcreate:
    image:        mariadb
    restart:      always
    ports:
      - 3109:3306
    volumes:
      - type:     bind
        source:   ./conf/inits/sql_create_setup.sql
        target:   /docker-entrypoint-initdb.d/00_create_user_and_db.sql
      - type:     volume
        source:   create_db_volume
        target:   /var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
