version: "3.3"

volumes:
  db_data_volume: { }
  select_db_volume: { }
  update_db_volume: { }
  create_db_volume: { }

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: it4all
    volumes:
      - type: volume
        source: db_data_volume
        target: /var/lib/mysql
      - type: bind
        source: init.sql
        target: /docker-entrypoint-initdb.d/init.sql

  webtester:
    image: httpd:alpine
    restart: always
    ports:
      - "127.0.0.1:9080:80"
    volumes:
      - type: bind
        source: ./data/web/solutions/
        target: /usr/local/apache2/htdocs/

  sqlselect:
    image: mariadb
    restart: always
    ports:
      - "127.0.0.1:3107:3306"
    volumes:
      - type: bind
        source: ./conf/inits/init_db_scripts/
        target: /docker-entrypoint-initdb.d/
      - type: volume
        source: select_db_volume
        target: /var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  sqlchange:
    image: mariadb
    restart: always
    ports:
      - "127.0.0.1:3108:3306"
    volumes:
      - type: bind
        source: ./conf/inits/init_db_scripts/
        target: /docker-entrypoint-initdb.d/
      - type: volume
        source: update_db_volume
        target: /var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  sqlcreate:
    image: mariadb
    restart: always
    ports:
      - "127.0.0.1:3109:3306"
    volumes:
      - type: bind
        source: ./conf/inits/sql_create_setup.sql
        target: /docker-entrypoint-initdb.d/00_create_user_and_db.sql
      - type: volume
        source: create_db_volume
        target: /var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
