version: '2'

services:
    dbit4all:
        image:        mysql:8
        restart:      always
        ports:
        - 3106:3306
        volumes:
        - ./inits/sql_main_setup.sql:/docker-entrypoint-initdb.d/sql_init.sql
        environment:
        - MYSQL_ROOT_PASSWORD=sT8aV#k7
    
    sqlselect:
        image:        mysql:8
        restart:      always
        ports:
        - 3107:3306
        volumes:
        - ./inits/sql_select_setup.sql:/docker-entrypoint-initdb.d/sql_init.sql
        environment:
        - MYSQL_ROOT_PASSWORD=sT8aV#k7
    
    sqlchange:
        image:        mysql:8
        restart:      always
        ports:
        - 3108:3306
        volumes:
        - ./inits/sql_change_setup.sql:/docker-entrypoint-initdb.d/sql_init.sql
        environment:
        - MYSQL_ROOT_PASSWORD=sT8aV#k7

    sqlcreate:
        image:        mysql:8
        restart:      always
        ports:
        - 3109:3306
        volumes:
        - ./inits/sql_create_setup.sql:/docker-entrypoint-initdb.d/sql_init.sql
        environment:
        - MYSQL_ROOT_PASSWORD=sT8aV#k7